version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # - image: starefossen/ruby-node:2-8
      - image: circleci/ruby:2.4.1-node
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v2-dependencies-{{ checksum "Gemfile.lock" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v2-dependencies-

      - run:
          name: Install Bundler
          command: gem install bundler

      - run:
          name: Ruby dependencies
          command: bundle install

      - run:
          name: Node dependencies
          # command: sudo npm install -g firebase-tools
          command: sudo npm install -g firebase-tools@3.9.1 --unsafe-perm

      - save_cache:
          paths:
            - /usr/local/bundle
            - /usr/local/lib/node_modules
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Build
          command: bundle exec jekyll build --verbose
      
      - run:
          name: Test
          command: bundle exec htmlproofer ./_site --check-html --disable-external

      - run:
          name: Deploy
          # run 'firebase login:ci' in your local terminal to get token
          # command: firebase deploy --token "1/H0k0awhqgLYnEDb7vgKG8tSJKMQARZ7om3_QiG7nATE"
          command: firebase deploy --token=1/H0k0awhqgLYnEDb7vgKG8tSJKMQARZ7om3_QiG7nATE --non-interactive